# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Official Ubuntu Server 14.04 LTS (Trusty Tahr) builds
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :shell, :path => "vagrant-provision.sh"

end
