VAGRANTFILE_API_VERSION = "2"

#
# provision script; pull Docker image
#
docker_image = "williamyeh/show-kernel-info"
$script = <<SCRIPT
echo Downloading Docker image: \'#{docker_image}\'...
echo This may take minutes...

docker pull #{docker_image}
if [[ $? -eq 0 ]]; then
  echo Done.
else
  echo ERROR when pulling Docker image!
fi
SCRIPT


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "yungsang/coreos"
  config.vm.synced_folder "..", "/vagrant", id: "core", type: "nfs", mount_options: ['nolock,vers=3,udp']

  config.vm.provision :shell, :inline => $script

  config.vm.provider "virtualbox" do |vb|
    config.vm.network "private_network", ip: "192.168.10.10"
  end

end
