VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "yungsang/coreos"
  config.vm.synced_folder "..", "/vagrant", id: "core", type: "nfs", mount_options: ['nolock,vers=3,udp']

  config.vm.provision "docker", images: ["williamyeh/show-kernel-info"]

  config.vm.provider "virtualbox" do |vb|
    config.vm.network "private_network", ip: "192.168.10.10"
  end

end
