# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Ubuntu 14.04 with docker installed & tuned kernel settings
  config.vm.box = "3scale/docker"

  config.vm.synced_folder ".", "/vagrant"

end