VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "williamyeh/ubuntu-trusty64-docker"
  config.vm.synced_folder "..", "/vagrant"

  config.vm.provision "docker", images: ["williamyeh/show-kernel-info"]
end
